In [1]:
import pandas as pd
import numpy as np
import csv
import time
from datetime import datetime
from datetime import date

## 2019-08
-User Type (Customer = 24-hour pass or 3-day pass user; Subscriber = Annual Member)

In [2]:
#Import Jan CSV for Year: 2019-08
df_2019_08=pd.read_csv("Resources/Citibike_DataSource/JC-201908-citibike-tripdata.csv")

In [3]:
df_2019_08.columns

Index(['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender'],
      dtype='object')

In [4]:
# Rename Trip Duration to reflect values are in seconds
# https://www.citibikenyc.com/system-data
df_2019_08=df_2019_08.rename(columns={'tripduration':'tripduration(seconds)'
                                      ,'start station id':'start_station_id'
                                      ,'start station name':'start_station_name'
                                      ,'start station latitude': 'start_station_latitude'
                                      ,'start station longitude':'start_station_longitude'
                                      ,'end station id':'end_station_id'
                                      ,'end station name': 'end_station_name'
                                      ,'end station latitude':'end_station_latitude'
                                      ,'end station longitude':'end_station_longitude'
                                      ,'birth year':'birth_year'})

In [5]:
df_2019_08.head(2)

tripduration(seconds)                 starttime                  stoptime  \
0                    261  2019-08-01 00:14:55.9900  2019-08-01 00:19:17.4780   
1                    172  2019-08-01 00:23:06.9910  2019-08-01 00:25:59.1480   

   start_station_id start_station_name  start_station_latitude  \
0              3205  JC Medical Center                40.71654   
1              3279        Dixon Mills                40.72163   

   start_station_longitude  end_station_id    end_station_name  \
0               -74.049638            3192  Liberty Light Rail   
1               -74.049968            3186       Grove St PATH   

   end_station_latitude  end_station_longitude  bikeid    usertype  \
0             40.711242             -74.055701   26268  Subscriber   
1             40.719586             -74.043117   26162  Subscriber   

   birth_year  gender  
0        1980       1  
1        1996       1

In [6]:
df_2019_08.dtypes

tripduration(seconds)        int64
starttime                   object
stoptime                    object
start_station_id             int64
start_station_name          object
start_station_latitude     float64
start_station_longitude    float64
end_station_id               int64
end_station_name            object
end_station_latitude       float64
end_station_longitude      float64
bikeid                       int64
usertype                    object
birth_year                   int64
gender                       int64
dtype: object

## Identified na values & filled with "0" or "Unknown" 

In [7]:
#Check how many null values in each column
df_2019_08.isnull().sum()

tripduration(seconds)      0
starttime                  0
stoptime                   0
start_station_id           0
start_station_name         0
start_station_latitude     0
start_station_longitude    0
end_station_id             0
end_station_name           0
end_station_latitude       0
end_station_longitude      0
bikeid                     0
usertype                   0
birth_year                 0
gender                     0
dtype: int64

## Work on birth_year & calculate age

In [8]:
df_2019_08['birth_year']=df_2019_08['birth_year'].fillna(0)

In [9]:
df_2019_08['birth_year']=df_2019_08.birth_year.astype(int)

In [10]:
df_2019_08.birth_year.unique()

array([1980, 1996, 1991, 1988, 1960, 1981, 1985, 1978, 1969, 1987, 1984,
       1971, 1986, 1998, 1964, 1995, 1982, 1966, 1967, 1994, 1989, 1962,
       1973, 1961, 1977, 1975, 1974, 1979, 1976, 1958, 1983, 1970, 1990,
       1993, 1972, 1992, 1963, 1954, 1968, 1956, 1965, 1951, 1955, 1997,
       1959, 1953, 1944, 2000, 2002, 1999, 1888, 1957, 1949, 1952, 1940,
       2001, 2003, 1950, 1887, 1946, 1947, 1948, 1900, 1905], dtype=int64)

In [11]:
# Add column to calculate age
df_2019_08['as_of_year']=2019
df_2019_08['month']= 'August'
df_2019_08['season']= 'Summer'

# Use Data Year minus birth_year at the time to obtain raider's age
df_2019_08['Age']=df_2019_08.as_of_year-df_2019_08.birth_year

In [12]:
a = df_2019_08['Age'].unique()
a.sort()
a

array([ 16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
        42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,
        55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,
        68,  69,  70,  71,  72,  73,  75,  79, 114, 119, 131, 132],
      dtype=int64)

In [13]:
df_2019_08['Age'].values[df_2019_08['Age'] > 85] = 0

In [14]:
b = df_2019_08['Age'].unique()
b.sort()
b

array([ 0, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
       66, 67, 68, 69, 70, 71, 72, 73, 75, 79], dtype=int64)

In [15]:
df_2019_08.dtypes

tripduration(seconds)        int64
starttime                   object
stoptime                    object
start_station_id             int64
start_station_name          object
start_station_latitude     float64
start_station_longitude    float64
end_station_id               int64
end_station_name            object
end_station_latitude       float64
end_station_longitude      float64
bikeid                       int64
usertype                    object
birth_year                   int32
gender                       int64
as_of_year                   int64
month                       object
season                      object
Age                          int64
dtype: object

In [16]:
df_2019_08['birth_year']=df_2019_08.birth_year.astype(int)

In [17]:
df_2019_08.dtypes

tripduration(seconds)        int64
starttime                   object
stoptime                    object
start_station_id             int64
start_station_name          object
start_station_latitude     float64
start_station_longitude    float64
end_station_id               int64
end_station_name            object
end_station_latitude       float64
end_station_longitude      float64
bikeid                       int64
usertype                    object
birth_year                   int32
gender                       int64
as_of_year                   int64
month                       object
season                      object
Age                          int64
dtype: object

## Standarized Format for Start Time and End Time 
-.strftime("%Y/%m/%d %H:%M:%S")

In [18]:
#Standarized Start Time
start_time_201908=[datetime.strptime(x,"%Y-%m-%d %H:%M:%S.%f").strftime("%Y/%m/%d %H:%M:%S") for x in df_2019_08['starttime'].values.tolist()]

In [19]:
#Standarized Start Time
end_time_201908=[datetime.strptime(x,"%Y-%m-%d %H:%M:%S.%f").strftime("%Y/%m/%d %H:%M:%S") for x in df_2019_08['stoptime'].values.tolist()]

In [20]:
# Add Columns
df_2019_08['trip_start_time']=start_time_201908
df_2019_08['trip_end_time']=end_time_201908

## Clean the Gender column
--Gender (Zero=unknown; 1=male; 2=female) 

In [21]:
#Replace Gender Column
# Gender (Zero=unknown; 1=male; 2=female)
df_2019_08['gender']=df_2019_08['gender'].replace([0], 'Unknown')
df_2019_08['gender']=df_2019_08['gender'].replace([1], 'Male')
df_2019_08['gender']=df_2019_08['gender'].replace([2], 'Female')

In [22]:
df_2019_08.isnull().sum()

tripduration(seconds)      0
starttime                  0
stoptime                   0
start_station_id           0
start_station_name         0
start_station_latitude     0
start_station_longitude    0
end_station_id             0
end_station_name           0
end_station_latitude       0
end_station_longitude      0
bikeid                     0
usertype                   0
birth_year                 0
gender                     0
as_of_year                 0
month                      0
season                     0
Age                        0
trip_start_time            0
trip_end_time              0
dtype: int64

In [23]:
df_2019_08.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48711 entries, 0 to 48710
Data columns (total 21 columns):
tripduration(seconds)      48711 non-null int64
starttime                  48711 non-null object
stoptime                   48711 non-null object
start_station_id           48711 non-null int64
start_station_name         48711 non-null object
start_station_latitude     48711 non-null float64
start_station_longitude    48711 non-null float64
end_station_id             48711 non-null int64
end_station_name           48711 non-null object
end_station_latitude       48711 non-null float64
end_station_longitude      48711 non-null float64
bikeid                     48711 non-null int64
usertype                   48711 non-null object
birth_year                 48711 non-null int32
gender                     48711 non-null object
as_of_year                 48711 non-null int64
month                      48711 non-null object
season                     48711 non-null object
Age        

## Export to CSV

In [24]:
# Write to CSV
df_2019_08.to_csv("Resources/df_2019_08.csv", index=False)