In [1]:
import pandas as pd
import numpy as np
import csv
import time
from datetime import datetime
from datetime import date

## 2018-01
-User Type (Customer = 24-hour pass or 3-day pass user; Subscriber = Annual Member)

In [2]:
#Import Jan CSV for Year: 2018-01
df_2018_01=pd.read_csv("Resources/Citibike_DataSource/JC-201801-citibike-tripdata.csv")

In [3]:
df_2018_01.columns

Index(['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender'],
      dtype='object')

In [4]:
# Rename Trip Duration to reflect values are in seconds
# https://www.citibikenyc.com/system-data
df_2018_01=df_2018_01.rename(columns={'tripduration':'tripduration(seconds)'
                                      ,'start station id':'start_station_id'
                                      ,'start station name':'start_station_name'
                                      ,'start station latitude': 'start_station_latitude'
                                      ,'start station longitude':'start_station_longitude'
                                      ,'end station id':'end_station_id'
                                      ,'end station name': 'end_station_name'
                                      ,'end station latitude':'end_station_latitude'
                                      ,'end station longitude':'end_station_longitude'
                                      ,'birth year':'birth_year'})

In [5]:
df_2018_01.head(2)

tripduration(seconds)                 starttime                  stoptime  \
0                    932  2018-01-01 02:06:17.5410  2018-01-01 02:21:50.0270   
1                    550  2018-01-01 12:06:18.0390  2018-01-01 12:15:28.4430   

   start_station_id start_station_name  start_station_latitude  \
0              3183     Exchange Place               40.716247   
1              3183     Exchange Place               40.716247   

   start_station_longitude  end_station_id end_station_name  \
0               -74.033459            3199     Newport Pkwy   
1               -74.033459            3199     Newport Pkwy   

   end_station_latitude  end_station_longitude  bikeid    usertype  \
0             40.728745             -74.032108   31929  Subscriber   
1             40.728745             -74.032108   31845  Subscriber   

   birth_year  gender  
0        1992       1  
1        1969       2

In [6]:
df_2018_01.dtypes

tripduration(seconds)        int64
starttime                   object
stoptime                    object
start_station_id             int64
start_station_name          object
start_station_latitude     float64
start_station_longitude    float64
end_station_id               int64
end_station_name            object
end_station_latitude       float64
end_station_longitude      float64
bikeid                       int64
usertype                    object
birth_year                   int64
gender                       int64
dtype: object

## Identified na values & filled with "0" or "Unknown" 

In [7]:
#Check how many null values in each column
df_2018_01.isnull().sum()

tripduration(seconds)      0
starttime                  0
stoptime                   0
start_station_id           0
start_station_name         0
start_station_latitude     0
start_station_longitude    0
end_station_id             0
end_station_name           0
end_station_latitude       0
end_station_longitude      0
bikeid                     0
usertype                   0
birth_year                 0
gender                     0
dtype: int64

In [8]:
df_2018_01.usertype.unique()

array(['Subscriber', 'Customer'], dtype=object)

## Work on birth_year & calculate age
-Note: any rider age greater than '85', it will be replce with age '0'

In [9]:
df_2018_01.birth_year.unique()

array([1992, 1969, 1946, 1994, 1991, 1982, 1958, 1989, 1960, 1976, 1985,
       1974, 1968, 1988, 1990, 1980, 1995, 1981, 1978, 1983, 1966, 1965,
       1986, 1971, 1954, 1993, 1970, 1984, 1987, 1975, 1964, 1962, 1955,
       1963, 1999, 1957, 1956, 1972, 1973, 1941, 1952, 1977, 1967, 1961,
       1959, 1979, 1949, 1998, 1931, 1997, 1887, 1950, 1953, 1947, 1996,
       1948], dtype=int64)

In [10]:
df_2018_01['as_of_year']=2018
df_2018_01['month']= 'January'
df_2018_01['season']= 'Winter'

# Use Data Year minus birth_year at the time to obtain raider's age
df_2018_01['Age']=df_2018_01.as_of_year-df_2018_01.birth_year

In [11]:
a = df_2018_01['Age'].unique()
a.sort()
a

array([ 19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,
        32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,
        45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
        58,  59,  60,  61,  62,  63,  64,  65,  66,  68,  69,  70,  71,
        72,  77,  87, 131], dtype=int64)

In [12]:
df_2018_01['Age'].values[df_2018_01['Age'] > 85] = 0

In [13]:
b = df_2018_01['Age'].unique()
b.sort()
b

array([ 0, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 68, 69,
       70, 71, 72, 77], dtype=int64)

In [14]:
df_2018_01['birth_year']=df_2018_01.birth_year.astype(int)

In [15]:
df_2018_01.dtypes

tripduration(seconds)        int64
starttime                   object
stoptime                    object
start_station_id             int64
start_station_name          object
start_station_latitude     float64
start_station_longitude    float64
end_station_id               int64
end_station_name            object
end_station_latitude       float64
end_station_longitude      float64
bikeid                       int64
usertype                    object
birth_year                   int32
gender                       int64
as_of_year                   int64
month                       object
season                      object
Age                          int64
dtype: object

In [16]:
df_2018_01.head()

tripduration(seconds)                 starttime                  stoptime  \
0                    932  2018-01-01 02:06:17.5410  2018-01-01 02:21:50.0270   
1                    550  2018-01-01 12:06:18.0390  2018-01-01 12:15:28.4430   
2                    510  2018-01-01 12:06:56.9780  2018-01-01 12:15:27.8100   
3                    354  2018-01-01 14:53:10.1860  2018-01-01 14:59:05.0960   
4                    250  2018-01-01 17:34:30.1920  2018-01-01 17:38:40.9840   

   start_station_id start_station_name  start_station_latitude  \
0              3183     Exchange Place               40.716247   
1              3183     Exchange Place               40.716247   
2              3183     Exchange Place               40.716247   
3              3183     Exchange Place               40.716247   
4              3183     Exchange Place               40.716247   

   start_station_longitude  end_station_id end_station_name  \
0               -74.033459            3199     Newport Pkwy   
1               -74.033459            3199     Newport Pkwy   
2               -74.033459            3199     Newport Pkwy   
3               -74.033459            3267     Morris Canal   
4               -74.033459            3639       Harborside   

   end_station_latitude  end_station_longitude  bikeid    usertype  \
0             40.728745             -74.032108   31929  Subscriber   
1             40.728745             -74.032108   31845  Subscriber   
2             40.728745             -74.032108   31708  Subscriber   
3             40.712419             -74.038526   31697  Subscriber   
4             40.719252             -74.034234   31861  Subscriber   

   birth_year  gender  as_of_year    month  season  Age  
0        1992       1        2018  January  Winter   26  
1        1969       2        2018  January  Winter   49  
2        1946       1        2018  January  Winter   72  
3        1994       1        2018  January  Winter   24  
4        1991       1        2018  January  Winter   27

## Standarized Format for Start Time and End Time 
-.strftime("%Y/%m/%d %H:%M:%S")

In [17]:
#Standarized Start Time and End time 
start_time_201801=[datetime.strptime(x,"%Y-%m-%d %H:%M:%S.%f").strftime("%Y/%m/%d %H:%M:%S") for x in df_2018_01['starttime'].values.tolist()]
end_time_201801=[datetime.strptime(x,"%Y-%m-%d %H:%M:%S.%f").strftime("%Y/%m/%d %H:%M:%S") for x in df_2018_01['stoptime'].values.tolist()]


In [18]:
# Add Columns
df_2018_01['trip_start_time']=start_time_201801
df_2018_01['trip_end_time']=end_time_201801

## Clean the Gender column
--Gender (Zero=unknown; 1=male; 2=female) 

In [19]:
#Replace Gender Column
# Gender (Zero=unknown; 1=male; 2=female)
df_2018_01['gender']=df_2018_01['gender'].replace([0], 'Unknown')
df_2018_01['gender']=df_2018_01['gender'].replace([1], 'Male')
df_2018_01['gender']=df_2018_01['gender'].replace([2], 'Female')

In [20]:
df_2018_01.isnull().sum()

tripduration(seconds)      0
starttime                  0
stoptime                   0
start_station_id           0
start_station_name         0
start_station_latitude     0
start_station_longitude    0
end_station_id             0
end_station_name           0
end_station_latitude       0
end_station_longitude      0
bikeid                     0
usertype                   0
birth_year                 0
gender                     0
as_of_year                 0
month                      0
season                     0
Age                        0
trip_start_time            0
trip_end_time              0
dtype: int64

In [21]:
df_2018_01.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12677 entries, 0 to 12676
Data columns (total 21 columns):
tripduration(seconds)      12677 non-null int64
starttime                  12677 non-null object
stoptime                   12677 non-null object
start_station_id           12677 non-null int64
start_station_name         12677 non-null object
start_station_latitude     12677 non-null float64
start_station_longitude    12677 non-null float64
end_station_id             12677 non-null int64
end_station_name           12677 non-null object
end_station_latitude       12677 non-null float64
end_station_longitude      12677 non-null float64
bikeid                     12677 non-null int64
usertype                   12677 non-null object
birth_year                 12677 non-null int32
gender                     12677 non-null object
as_of_year                 12677 non-null int64
month                      12677 non-null object
season                     12677 non-null object
Age        

## Export to CSV

In [22]:
# Write to CSV
df_2018_01.to_csv("Resources/df_2018_01.csv", index=False)