In [1]:
import pandas as pd
import numpy as np
import csv
import time
from datetime import datetime
from datetime import date

## 2017-08
-User Type (Customer = 24-hour pass or 3-day pass user; Subscriber = Annual Member)

In [2]:
#Import Jan CSV for Year: 2017-08
df_2017_08=pd.read_csv("Resources/Citibike_DataSource/JC-201708-citibike-tripdata.csv")

In [3]:
df_2017_08.columns

Index(['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender'],
      dtype='object')

In [4]:
# Rename Trip Duration to reflect values are in seconds
# https://www.citibikenyc.com/system-data
df_2017_08=df_2017_08.rename(columns={'tripduration':'tripduration(seconds)'
                                      ,'start station id':'start_station_id'
                                      ,'start station name':'start_station_name'
                                      ,'start station latitude': 'start_station_latitude'
                                      ,'start station longitude':'start_station_longitude'
                                      ,'end station id':'end_station_id'
                                      ,'end station name': 'end_station_name'
                                      ,'end station latitude':'end_station_latitude'
                                      ,'end station longitude':'end_station_longitude'
                                      ,'birth year':'birth_year'})

In [5]:
df_2017_08.head(2)

tripduration(seconds)            starttime             stoptime  \
0                   2110  2017-08-01 00:00:00  2017-08-01 00:35:11   
1                    160  2017-08-01 00:00:10  2017-08-01 00:02:51   

   start_station_id      start_station_name  start_station_latitude  \
0               470         W 20 St & 8 Ave               40.743453   
1               348  W Broadway & Spring St               40.724910   

   start_station_longitude  end_station_id          end_station_name  \
0               -74.000040            3289   W 90 St & Amsterdam Ave   
1               -74.001547             151  Cleveland Pl & Spring St   

   end_station_latitude  end_station_longitude  bikeid    usertype  \
0             40.790179             -73.972889   20954  Subscriber   
1             40.722104             -73.997249   15164  Subscriber   

   birth_year  gender  
0      1978.0       2  
1      1978.0       1

In [6]:
df_2017_08.dtypes

tripduration(seconds)        int64
starttime                   object
stoptime                    object
start_station_id             int64
start_station_name          object
start_station_latitude     float64
start_station_longitude    float64
end_station_id               int64
end_station_name            object
end_station_latitude       float64
end_station_longitude      float64
bikeid                       int64
usertype                    object
birth_year                 float64
gender                       int64
dtype: object

## Identified na values & filled with "0" or "Unknown" 

In [7]:
#Check how many null values in each column
df_2017_08.isnull().sum()

tripduration(seconds)           0
starttime                       0
stoptime                        0
start_station_id                0
start_station_name              0
start_station_latitude          0
start_station_longitude         0
end_station_id                  0
end_station_name                0
end_station_latitude            0
end_station_longitude           0
bikeid                          0
usertype                        0
birth_year                 224716
gender                          0
dtype: int64

## Work on birth_year & calculate age

In [8]:
df_2017_08['birth_year']=df_2017_08['birth_year'].fillna(0)

In [9]:
df_2017_08['birth_year']=df_2017_08.birth_year.astype(int)

In [10]:
df_2017_08.birth_year.unique()

array([1978, 1962, 1990, 1983, 1967, 1986, 1972, 1989, 1955, 1985, 1987,
       1952,    0, 1976, 1974, 1982, 1992, 1988, 1993, 1971, 1979, 1994,
       1968, 1996, 1973, 1984, 1981, 1977, 1991, 1999, 1959, 1995, 1969,
       1965, 1951, 1956, 2000, 1970, 1975, 1964, 1966, 1980, 1963, 1961,
       1998, 1997, 1958, 1953, 1960, 1932, 1954, 1957, 1940, 1944, 1949,
       1950, 1946, 1947, 1948, 1943, 1945, 1913, 1942, 1941, 1934, 1938,
       1885, 1900, 1923, 2001, 1935, 1933, 1936, 1910, 1912, 1917, 1901,
       1939, 1899, 1937, 1893, 1918, 1888, 1931, 1887, 1896, 1928, 1929,
       1921, 1915, 1886, 1895, 1930, 1907, 1920, 1905, 1916, 1890],
      dtype=int64)

In [11]:
# Add column to calculate age
df_2017_08['as_of_year']=2017
df_2017_08['month']= 'August'
df_2017_08['season']= 'Summer'

# Use Data Year minus birth_year at the time to obtain raider's age
df_2017_08['Age']=df_2017_08.as_of_year-df_2017_08.birth_year

In [12]:
a = df_2017_08['Age'].unique()
a.sort()
a

array([  16,   17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
         27,   28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
         38,   39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
         49,   50,   51,   52,   53,   54,   55,   56,   57,   58,   59,
         60,   61,   62,   63,   64,   65,   66,   67,   68,   69,   70,
         71,   72,   73,   74,   75,   76,   77,   78,   79,   80,   81,
         82,   83,   84,   85,   86,   87,   88,   89,   94,   96,   97,
         99,  100,  101,  102,  104,  105,  107,  110,  112,  116,  117,
        118,  121,  122,  124,  127,  129,  130,  131,  132, 2017],
      dtype=int64)

In [13]:
df_2017_08['Age'].values[df_2017_08['Age'] > 85] = 0

In [14]:
b = df_2017_08['Age'].unique()
b.sort()
b

array([ 0, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
       66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82,
       83, 84, 85], dtype=int64)

In [15]:
df_2017_08.dtypes

tripduration(seconds)        int64
starttime                   object
stoptime                    object
start_station_id             int64
start_station_name          object
start_station_latitude     float64
start_station_longitude    float64
end_station_id               int64
end_station_name            object
end_station_latitude       float64
end_station_longitude      float64
bikeid                       int64
usertype                    object
birth_year                   int32
gender                       int64
as_of_year                   int64
month                       object
season                      object
Age                          int64
dtype: object

In [16]:
df_2017_08['birth_year']=df_2017_08.birth_year.astype(int)

In [17]:
df_2017_08.dtypes

tripduration(seconds)        int64
starttime                   object
stoptime                    object
start_station_id             int64
start_station_name          object
start_station_latitude     float64
start_station_longitude    float64
end_station_id               int64
end_station_name            object
end_station_latitude       float64
end_station_longitude      float64
bikeid                       int64
usertype                    object
birth_year                   int32
gender                       int64
as_of_year                   int64
month                       object
season                      object
Age                          int64
dtype: object

## Standarized Format for Start Time and End Time 
-.strftime("%Y/%m/%d %H:%M:%S")

In [18]:
#Standarized Start Time
start_time_201708=[datetime.strptime(x,"%Y-%m-%d %H:%M:%S").strftime("%Y/%m/%d %H:%M:%S") for x in df_2017_08['starttime'].values.tolist()]

In [19]:
#Standarized Start Time
end_time_201708=[datetime.strptime(x,"%Y-%m-%d %H:%M:%S").strftime("%Y/%m/%d %H:%M:%S") for x in df_2017_08['stoptime'].values.tolist()]

In [20]:
# Add Columns
df_2017_08['trip_start_time']=start_time_201708
df_2017_08['trip_end_time']=end_time_201708

## Clean the Gender column
--Gender (Zero=unknown; 1=male; 2=female) 

In [21]:
#Replace Gender Column
# Gender (Zero=unknown; 1=male; 2=female)
df_2017_08['gender']=df_2017_08['gender'].replace([0], 'Unknown')
df_2017_08['gender']=df_2017_08['gender'].replace([1], 'Male')
df_2017_08['gender']=df_2017_08['gender'].replace([2], 'Female')

In [22]:
df_2017_08.isnull().sum()

tripduration(seconds)      0
starttime                  0
stoptime                   0
start_station_id           0
start_station_name         0
start_station_latitude     0
start_station_longitude    0
end_station_id             0
end_station_name           0
end_station_latitude       0
end_station_longitude      0
bikeid                     0
usertype                   0
birth_year                 0
gender                     0
as_of_year                 0
month                      0
season                     0
Age                        0
trip_start_time            0
trip_end_time              0
dtype: int64

In [23]:
df_2017_08.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1816498 entries, 0 to 1816497
Data columns (total 21 columns):
tripduration(seconds)      int64
starttime                  object
stoptime                   object
start_station_id           int64
start_station_name         object
start_station_latitude     float64
start_station_longitude    float64
end_station_id             int64
end_station_name           object
end_station_latitude       float64
end_station_longitude      float64
bikeid                     int64
usertype                   object
birth_year                 int32
gender                     object
as_of_year                 int64
month                      object
season                     object
Age                        int64
trip_start_time            object
trip_end_time              object
dtypes: float64(4), int32(1), int64(6), object(10)
memory usage: 284.1+ MB


## Export to CSV

In [24]:
# Write to CSV
df_2017_08.to_csv("Resources/df_2017_08.csv", index=False)